package mx.uatx.siiaback.serviciosEscolares.entities;
// Generated 9/03/2010 11:26:21 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeAxBloquePreguntaOV generated by hbm2java
 */
@Entity
@Table(schema = "SERESC", name = "SEAXSOLICITUDESEXAMENES")
public class SeAxSolicitudesExamenes implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -220264087499181588L;

	@Id
	@Basic(optional = false)
	@SequenceGenerator(name = "GENIDSOLICITUDEXAMEN", sequenceName = "SERESC.IDSOLICITUDEXAMEN", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GENIDSOLICITUDEXAMEN")
	@Column(name = "IDSOLICITUDEXAMEN")
	private Long lngIdSolicitudExamen;

	@Column(name = "IDALUMNOCARGA")
	private Long lngIdAlumnoCarga;

	@Column(name = "FCSOLICITUD")
	@Temporal(TemporalType.TIMESTAMP)
	private Date fcSolicitud;

	@Column(name = "CLESTATUSSOLICITUD")
	private Integer intCveEstatusSolicitud;

	@Column(name = "FCAUDIT")
	@Temporal(TemporalType.TIMESTAMP)
	private Date fcAudit;

	@Column(name = "USUARIOAUDIT", length = 30)
	private String strUsuarioAudit;

	@OneToMany(mappedBy = "solicitudExamen", cascade = CascadeType.PERSIST)
	private Set<SeDtSolicitudesExamenes> hasSeDtSolicitudesExamenes = new HashSet<>();

	public Long getLngIdSolicitudExamen() {
		return lngIdSolicitudExamen;
	}

	public void setLngIdSolicitudExamen(Long lngIdSolicitudExamen) {
		this.lngIdSolicitudExamen = lngIdSolicitudExamen;
	}

	public Long getLngIdAlumnoCarga() {
		return lngIdAlumnoCarga;
	}

	public void setLngIdAlumnoCarga(Long lngIdAlumnoCarga) {
		this.lngIdAlumnoCarga = lngIdAlumnoCarga;
	}

	public Date getFcSolicitud() {
		return fcSolicitud;
	}

	public void setFcSolicitud(Date fcSolicitud) {
		this.fcSolicitud = fcSolicitud;
	}

	public Integer getIntCveEstatusSolicitud() {
		return intCveEstatusSolicitud;
	}

	public void setIntCveEstatusSolicitud(Integer intCveEstatusSolicitud) {
		this.intCveEstatusSolicitud = intCveEstatusSolicitud;
	}

	public Date getFcAudit() {
		return fcAudit;
	}

	public void setFcAudit(Date fcAudit) {
		this.fcAudit = fcAudit;
	}

	public String getStrUsuarioAudit() {
		return strUsuarioAudit;
	}

	public void setStrUsuarioAudit(String strUsuarioAudit) {
		this.strUsuarioAudit = strUsuarioAudit;
	}

	public Set<SeDtSolicitudesExamenes> getHasSeDtSolicitudesExamenes() {
		return hasSeDtSolicitudesExamenes;
	}

	public void setHasSeDtSolicitudesExamenes(Set<SeDtSolicitudesExamenes> hasSeDtSolicitudesExamenes) {
		this.hasSeDtSolicitudesExamenes = hasSeDtSolicitudesExamenes;
	}

}
