package mx.uatx.siiaback.serviciosEscolares.entities;


// Generated 9/03/2010 11:26:21 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeAxAreaEstudioProgramaOV generated by hbm2java
 */
@Entity
@Table(schema = "SERESC", name = "SEAXAREAESTUDIOPROGRAMAOV")
@NamedQueries({
    @NamedQuery(name = "SeAxAreaEstudioProgramaOV.listaProgramasEstudio",
    		query = "select aep from SeAxAreaEstudioProgramaOV aep " +
			" where aep.seCtAreaEstudioOV.idareaestudioov in (:idAreaEstudioOV)")
})
public class SeAxAreaEstudioProgramaOV implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idareaestudioprogramaov;
	private SeCtAreaEstudioOV seCtAreaEstudioOV;
	private SeCtProgramaEducativo seCtProgramaEducativo;
	private Date fcaudit;
	private String usuarioaudit;

	public SeAxAreaEstudioProgramaOV() {
	}

	public SeAxAreaEstudioProgramaOV(int idareaestudioprogramaov,
			SeCtAreaEstudioOV seCtAreaEstudioOV,
			SeCtProgramaEducativo seCtProgramaEducativo) {
		this.idareaestudioprogramaov = idareaestudioprogramaov;
		this.seCtAreaEstudioOV = seCtAreaEstudioOV;
		this.seCtProgramaEducativo = seCtProgramaEducativo;
	}
	public SeAxAreaEstudioProgramaOV(int idareaestudioprogramaov,
			SeCtAreaEstudioOV seCtAreaEstudioOV,
			SeCtProgramaEducativo seCtProgramaEducativo, Date fcaudit,
			String usuarioaudit) {
		this.idareaestudioprogramaov = idareaestudioprogramaov;
		this.seCtAreaEstudioOV = seCtAreaEstudioOV;
		this.seCtProgramaEducativo = seCtProgramaEducativo;
		this.fcaudit = fcaudit;
		this.usuarioaudit = usuarioaudit;
	}

	@Id
	@Column(name = "IDAREAESTUDIOPROGRAMAOV", unique = true, nullable = false, precision = 4, scale = 0)
	public int getIdareaestudioprogramaov() {
		return this.idareaestudioprogramaov;
	}

	public void setIdareaestudioprogramaov(int idareaestudioprogramaov) {
		this.idareaestudioprogramaov = idareaestudioprogramaov;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDAREAESTUDIOOV", nullable = false)
	
	public SeCtAreaEstudioOV getSeCtAreaEstudioOV() {
		return seCtAreaEstudioOV;
	}

	public void setSeCtAreaEstudioOV(SeCtAreaEstudioOV seCtAreaEstudioOV) {
		this.seCtAreaEstudioOV = seCtAreaEstudioOV;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPROGRAMAEDUCATIVO", nullable = false)
	public SeCtProgramaEducativo getSeCtProgramaEducativo() {
		return seCtProgramaEducativo;
	}

	public void setSeCtProgramaEducativo(SeCtProgramaEducativo seCtProgramaEducativo) {
		this.seCtProgramaEducativo = seCtProgramaEducativo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FCAUDIT", length = 7)
	public Date getFcaudit() {
		return this.fcaudit;
	}

	public void setFcaudit(Date fcaudit) {
		this.fcaudit = fcaudit;
	}

	@Column(name = "USUARIOAUDIT", length = 30)
	public String getUsuarioaudit() {
		return this.usuarioaudit;
	}

	public void setUsuarioaudit(String usuarioaudit) {
		this.usuarioaudit = usuarioaudit;
	}

}
