package mx.uatx.siiaback.serviciosEscolares.entities;


// Generated 9/03/2010 11:26:21 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * SeAxMapaRespuestaOV generated by hbm2java
 */
@Entity
@Table(schema = "SERESC", name = "SEAXMAPASRESPUESTASOV")
public class SeAxMapaRespuestaOV implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idrespuestamapaov;
	private SeCtMapaOV seCtMapaOV;
	private SeAxBloquePreguntaOV seAxBloquePreguntaOV;
	private SeCtRespuestaOV seCtRespuestaOV;
	private Date fcaudit;
	private String usuarioaudit;

	public SeAxMapaRespuestaOV() {
	}

	public SeAxMapaRespuestaOV(int idrespuestamapaov,
			SeCtMapaOV seCtMapaOV,
			SeAxBloquePreguntaOV seAxBloquePreguntaOV,
			SeCtRespuestaOV seCtRespuestaOV) {
		this.idrespuestamapaov = idrespuestamapaov;
		this.seCtMapaOV = seCtMapaOV;
		this.seAxBloquePreguntaOV = seAxBloquePreguntaOV;
		this.seCtRespuestaOV = seCtRespuestaOV;
	}
	public SeAxMapaRespuestaOV(int idrespuestamapaov,
			SeCtMapaOV seCtMapaOV,
			SeAxBloquePreguntaOV seAxBloquePreguntaOV,
			SeCtRespuestaOV seCtRespuestaOV, Date fcaudit, String usuarioaudit) {
		this.idrespuestamapaov = idrespuestamapaov;
		this.seCtMapaOV = seCtMapaOV;
		this.seAxBloquePreguntaOV = seAxBloquePreguntaOV;
		this.seCtRespuestaOV = seCtRespuestaOV;
		this.fcaudit = fcaudit;
		this.usuarioaudit = usuarioaudit;
	}

	@Id
	@Column(name = "IDRESPUESTAMAPAOV", unique = true, nullable = false, precision = 8, scale = 0)
	
	public int getIdrespuestamapaov() {
		return this.idrespuestamapaov;
	}

	public void setIdrespuestamapaov(int idrespuestamapaov) {
		this.idrespuestamapaov = idrespuestamapaov;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDMAPAOV", nullable = false)
	
	public SeCtMapaOV getSeCtMapaOV() {
		return seCtMapaOV;
	}

	public void setSeCtMapaOV(SeCtMapaOV seCtMapaOV) {
		this.seCtMapaOV = seCtMapaOV;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDBLOQUEPREGUNTAOV", nullable = false)
	
	public SeAxBloquePreguntaOV getSeAxBloquePreguntaOV() {
		return seAxBloquePreguntaOV;
	}

	public void setSeAxBloquePreguntaOV(SeAxBloquePreguntaOV seAxBloquePreguntaOV) {
		this.seAxBloquePreguntaOV = seAxBloquePreguntaOV;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDRESPUESTAOV", nullable = false)
	
	public SeCtRespuestaOV getSeCtRespuestaOV() {
		return seCtRespuestaOV;
	}

	public void setSeCtRespuestaOV(SeCtRespuestaOV seCtRespuestaOV) {
		this.seCtRespuestaOV = seCtRespuestaOV;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FCAUDIT", length = 7)
	public Date getFcaudit() {
		return this.fcaudit;
	}

	public void setFcaudit(Date fcaudit) {
		this.fcaudit = fcaudit;
	}

	@Column(name = "USUARIOAUDIT", length = 30)
	public String getUsuarioaudit() {
		return this.usuarioaudit;
	}

	public void setUsuarioaudit(String usuarioaudit) {
		this.usuarioaudit = usuarioaudit;
	}

}
