package mx.uatx.siiaback.serviciosEscolares.entities;
// Generated 9/03/2010 11:26:21 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeAxSeccionCuestionarioOV generated by hbm2java
 */
@Entity
@Table(schema = "SERESC", name = "SEAXSECCIONESCUESTIONARIOSOV")
public class SeAxSeccionCuestionarioOV implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idseccionov;
	private String dsseccionov;
	private int clestatus;
	private Date fcaudit;
	private String usuarioaudit;
	private SeCtCuestionarioOV seCtCuestionarioOV;
	private int nmorden;
	private Set<SeCtBloqueSeccionOV> seCtBloqueSeccionOVs = new HashSet<SeCtBloqueSeccionOV>(
			0);

	public SeAxSeccionCuestionarioOV() {
	}

	public SeAxSeccionCuestionarioOV(int idseccionov, String dsseccionov,
			int clestatus, SeCtCuestionarioOV seCtCuestionarioOV, int nmorden) {
		this.idseccionov = idseccionov;
		this.dsseccionov = dsseccionov;
		this.clestatus = clestatus;
		this.seCtCuestionarioOV = seCtCuestionarioOV;
		this.nmorden = nmorden;
	}
	public SeAxSeccionCuestionarioOV(int idseccionov, String dsseccionov,
			int clestatus, Date fcaudit, String usuarioaudit,
			SeCtCuestionarioOV seCtCuestionarioOV, int nmorden,
			Set<SeCtBloqueSeccionOV> seCtBloqueSeccionOVs) {
		this.idseccionov = idseccionov;
		this.dsseccionov = dsseccionov;
		this.clestatus = clestatus;
		this.fcaudit = fcaudit;
		this.usuarioaudit = usuarioaudit;
		this.seCtCuestionarioOV = seCtCuestionarioOV;
		this.nmorden = nmorden;
		this.seCtBloqueSeccionOVs = seCtBloqueSeccionOVs;
	}

	@Id
	@Column(name = "IDSECCIONOV", unique = true, nullable = false, precision = 3, scale = 0)
	public int getIdseccionov() {
		return this.idseccionov;
	}

	public void setIdseccionov(int idseccionov) {
		this.idseccionov = idseccionov;
	}

	@Column(name = "DSSECCIONOV", nullable = false, length = 50)
	public String getDsseccionov() {
		return this.dsseccionov;
	}

	public void setDsseccionov(String dsseccionov) {
		this.dsseccionov = dsseccionov;
	}

	@Column(name = "CLESTATUS", nullable = false, precision = 1, scale = 0)
	public int getClestatus() {
		return this.clestatus;
	}

	public void setClestatus(int clestatus) {
		this.clestatus = clestatus;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "FCAUDIT", length = 7)
	public Date getFcaudit() {
		return this.fcaudit;
	}

	public void setFcaudit(Date fcaudit) {
		this.fcaudit = fcaudit;
	}

	@Column(name = "USUARIOAUDIT", length = 30)
	public String getUsuarioaudit() {
		return this.usuarioaudit;
	}

	public void setUsuarioaudit(String usuarioaudit) {
		this.usuarioaudit = usuarioaudit;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCUESTIONARIO", nullable = false)
	public SeCtCuestionarioOV getSeCtCuestionarioOV() {
		return seCtCuestionarioOV;
	}

	public void setSeCtCuestionarioOV(SeCtCuestionarioOV seCtCuestionarioOV) {
		this.seCtCuestionarioOV = seCtCuestionarioOV;
	}

	@Column(name = "NMORDEN", nullable = false, precision = 3, scale = 0)
	public int getNmorden() {
		return this.nmorden;
	}

	public void setNmorden(int nmorden) {
		this.nmorden = nmorden;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "seAxSeccionCuestionarioOV")
	public Set<SeCtBloqueSeccionOV> getSeCtBloqueSeccionOVs() {
		return seCtBloqueSeccionOVs;
	}
	public void setSeCtBloqueSeccionOVs(
			Set<SeCtBloqueSeccionOV> seCtBloqueSeccionOVs) {
		this.seCtBloqueSeccionOVs = seCtBloqueSeccionOVs;
	}

}
