package mx.uatx.siiaback.serviciosEscolares.entities;
// Generated 9/03/2010 11:26:21 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeAxBloquePreguntaOV generated by hbm2java
 */
@Entity
@Table(schema = "SERESC", name = "SEAXBLOQUESPREGUNTASOV")
public class SeAxBloquePreguntaOV implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idbloquepreguntaov;
	private SeCtBloqueSeccionOV seCtBloqueSeccionOV;
	private String dspregunta;
	private int nmorden;
	private int clestatus;
	private Date fcaudit;
	private String usuarioaudit;
	private Set<SeAxMapaRespuestaOV> seAxMapaRespuestaOVs = new HashSet<SeAxMapaRespuestaOV>(
			0);
	

	public SeAxBloquePreguntaOV() {
	}

	public SeAxBloquePreguntaOV(int idbloquepreguntaov,
			SeCtBloqueSeccionOV seCtBloqueSeccionOV, String dspregunta,
			int nmorden, int clestatus) {
		this.idbloquepreguntaov = idbloquepreguntaov;
		this.seCtBloqueSeccionOV = seCtBloqueSeccionOV;
		this.dspregunta = dspregunta;
		this.nmorden = nmorden;
		this.clestatus = clestatus;
	}
	public SeAxBloquePreguntaOV(int idbloquepreguntaov,
			SeCtBloqueSeccionOV seCtBloqueSeccionOV, String dspregunta,
			int nmorden, int clestatus, Date fcaudit, String usuarioaudit,
			Set<SeAxMapaRespuestaOV> seAxMapaRespuestaOVs) {
		this.idbloquepreguntaov = idbloquepreguntaov;
		this.seCtBloqueSeccionOV = seCtBloqueSeccionOV;
		this.dspregunta = dspregunta;
		this.nmorden = nmorden;
		this.clestatus = clestatus;
		this.fcaudit = fcaudit;
		this.usuarioaudit = usuarioaudit;
		this.seAxMapaRespuestaOVs = seAxMapaRespuestaOVs;
	}

	@Id
	@Column(name = "IDBLOQUEPREGUNTAOV", unique = true, nullable = false, precision = 6, scale = 0)
	public int getIdbloquepreguntaov() {
		return this.idbloquepreguntaov;
	}

	public void setIdbloquepreguntaov(int idbloquepreguntaov) {
		this.idbloquepreguntaov = idbloquepreguntaov;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDBLOQUESECCIONOV", nullable = false)
	public SeCtBloqueSeccionOV getSeCtBloqueSeccionOV() {
		return seCtBloqueSeccionOV;
	}

	public void setSeCtBloqueSeccionOV(SeCtBloqueSeccionOV seCtBloqueSeccionOV) {
		this.seCtBloqueSeccionOV = seCtBloqueSeccionOV;
	}

	@Column(name = "DSPREGUNTA", nullable = false, length = 200)
	public String getDspregunta() {
		return this.dspregunta;
	}

	public void setDspregunta(String dspregunta) {
		this.dspregunta = dspregunta;
	}

	@Column(name = "NMORDEN", nullable = false, precision = 2, scale = 0)
	public int getNmorden() {
		return this.nmorden;
	}

	public void setNmorden(int nmorden) {
		this.nmorden = nmorden;
	}

	@Column(name = "CLESTATUS", nullable = false, precision = 1, scale = 0)
	public int getClestatus() {
		return this.clestatus;
	}

	public void setClestatus(int clestatus) {
		this.clestatus = clestatus;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "FCAUDIT", length = 7)
	public Date getFcaudit() {
		return this.fcaudit;
	}

	public void setFcaudit(Date fcaudit) {
		this.fcaudit = fcaudit;
	}

	@Column(name = "USUARIOAUDIT", length = 30)
	public String getUsuarioaudit() {
		return this.usuarioaudit;
	}

	public void setUsuarioaudit(String usuarioaudit) {
		this.usuarioaudit = usuarioaudit;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "seAxBloquePreguntaOV")
	public Set<SeAxMapaRespuestaOV> getSeAxMapaRespuestaOVs() {
		return seAxMapaRespuestaOVs;
	}
	public void setSeAxMapaRespuestaOVs(
			Set<SeAxMapaRespuestaOV> seAxMapaRespuestaOVs) {
		this.seAxMapaRespuestaOVs = seAxMapaRespuestaOVs;
	}

	

}
