package mx.uatx.siiaback.serviciosEscolares.entities;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Secttipostitulaciones generated by hbm2java
 */
@Entity
@Table(schema = "SERESC", name = "SECTTIPOSTITULACIONES")
public class SeCtTipoTitulacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String clTipoTitulacion;
	private String dsTipoTitulacion;
	private Date fcaudit;
	private String usuarioaudit;

	public SeCtTipoTitulacion() {
	}

	

	@Id
	@Column(name = "CLTIPOTITULACION", unique = true, nullable = false, length = 1)
	public String getClTipoTitulacion() {
		return clTipoTitulacion;
	}



	public void setClTipoTitulacion(String clTipoTitulacion) {
		this.clTipoTitulacion = clTipoTitulacion;
	}

	@Column(name = "DSTIPOTITULACION", length = 50)
	public String getDsTipoTitulacion() {
		return dsTipoTitulacion;
	}

	public void setDsTipoTitulacion(String dsTipoTitulacion) {
		this.dsTipoTitulacion = dsTipoTitulacion;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FCAUDIT", length = 7)
	public Date getFcaudit() {
		return this.fcaudit;
	}

	public void setFcaudit(Date fcaudit) {
		this.fcaudit = fcaudit;
	}

	@Column(name = "USUARIOAUDIT", length = 30)
	public String getUsuarioaudit() {
		return this.usuarioaudit;
	}

	public void setUsuarioaudit(String usuarioaudit) {
		this.usuarioaudit = usuarioaudit;
	}


}
