package mx.uatx.siiaback.serviciosEscolares.entities;
// Generated 9/03/2010 11:26:21 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeCtBloqueSeccionOV generated by hbm2java
 */
@Entity
@Table(schema = "SERESC", name = "SECTBLOQUESSECCIONESOV")
@NamedQueries({
	@NamedQuery(name="SeCtBloqueSeccionOV.listaSeCtBloqueSeccionOVPorSeccion", query="SELECT b FROM SeCtBloqueSeccionOV b " +
			"WHERE b.seAxSeccionCuestionarioOV.idseccionov = :idSeccionOV ORDER BY b.nmorden")
})
public class SeCtBloqueSeccionOV implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idbloqueseccionov;
	private SeAxSeccionCuestionarioOV seAxSeccionCuestionarioOV;
	private String dsbloqueseccionov;
	private int clestatus;
	private Date fcaudit;
	private String usuarioaudit;
	private int nmorden;
	private Set<SeAxBloquePreguntaOV> seAxBloquePreguntaOVs = new HashSet<SeAxBloquePreguntaOV>(
			0);

	public SeCtBloqueSeccionOV() {
	}

	public SeCtBloqueSeccionOV(int idbloqueseccionov,
			SeAxSeccionCuestionarioOV seAxSeccionCuestionarioOV,
			int clestatus) {
		this.idbloqueseccionov = idbloqueseccionov;
		this.seAxSeccionCuestionarioOV = seAxSeccionCuestionarioOV;
		this.clestatus = clestatus;
	}
	public SeCtBloqueSeccionOV(int idbloqueseccionov,
			SeAxSeccionCuestionarioOV seAxSeccionCuestionarioOV,
			String dsbloqueseccionov, int clestatus, Date fcaudit,
			String usuarioaudit,
			Set<SeAxBloquePreguntaOV> seAxBloquePreguntaOVs) {
		this.idbloqueseccionov = idbloqueseccionov;
		this.seAxSeccionCuestionarioOV = seAxSeccionCuestionarioOV;
		this.dsbloqueseccionov = dsbloqueseccionov;
		this.clestatus = clestatus;
		this.fcaudit = fcaudit;
		this.usuarioaudit = usuarioaudit;
		this.seAxBloquePreguntaOVs = seAxBloquePreguntaOVs;
	}

	@Id
	@Column(name = "IDBLOQUESECCIONOV", unique = true, nullable = false, precision = 2, scale = 0)
	public int getIdbloqueseccionov() {
		return this.idbloqueseccionov;
	}
	public void setIdbloqueseccionov(int idbloqueseccionov) {
		this.idbloqueseccionov = idbloqueseccionov;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDSECCIONOV", nullable = false)
	public SeAxSeccionCuestionarioOV getSeAxSeccionCuestionarioOV() {
		return seAxSeccionCuestionarioOV;
	}

	public void setSeAxSeccionCuestionarioOV(
			SeAxSeccionCuestionarioOV seAxSeccionCuestionarioOV) {
		this.seAxSeccionCuestionarioOV = seAxSeccionCuestionarioOV;
	}

	@Column(name = "DSBLOQUESECCIONOV", length = 30)
	public String getDsbloqueseccionov() {
		return this.dsbloqueseccionov;
	}

	public void setDsbloqueseccionov(String dsbloqueseccionov) {
		this.dsbloqueseccionov = dsbloqueseccionov;
	}

	@Column(name = "CLESTATUS", nullable = false, precision = 1, scale = 0)
	public int getClestatus() {
		return this.clestatus;
	}

	public void setClestatus(int clestatus) {
		this.clestatus = clestatus;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "FCAUDIT", length = 7)
	public Date getFcaudit() {
		return this.fcaudit;
	}

	public void setFcaudit(Date fcaudit) {
		this.fcaudit = fcaudit;
	}

	@Column(name = "USUARIOAUDIT", length = 30)
	public String getUsuarioaudit() {
		return this.usuarioaudit;
	}

	public void setUsuarioaudit(String usuarioaudit) {
		this.usuarioaudit = usuarioaudit;
	}
	
	@Column(name = "NMORDEN", precision = 2, scale = 0)
	public int getNmorden() {
		return nmorden;
	}

	public void setNmorden(int nmorden) {
		this.nmorden = nmorden;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "seCtBloqueSeccionOV")
	public Set<SeAxBloquePreguntaOV> getSeAxBloquePreguntaOVs() {
		return seAxBloquePreguntaOVs;
	}

	public void setSeAxBloquePreguntaOVs(
			Set<SeAxBloquePreguntaOV> seAxBloquePreguntaOVs) {
		this.seAxBloquePreguntaOVs = seAxBloquePreguntaOVs;
	}

}
