package mx.uatx.siiaback.serviciosEscolares.entities;


// Generated 28/05/2009 12:09:14 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Sectsttitulos generated by hbm2java
 */
@Entity
@Table(schema = "SERESC", name = "SECTSTTITULOS")
@NamedQueries({
	@NamedQuery(name="SeCtStTitulo.obtenerStTitulos", query="select e from SeCtStTitulo e order by e.clsttitulo")
})
public class SeCtStTitulo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String clsttitulo;
	private String dssttitulo;
	private Date fcaudit;
	private String usuarioaudit;

	public SeCtStTitulo() {
	}

	public SeCtStTitulo(String clsttitulo, String dssttitulo) {
		this.clsttitulo = clsttitulo;
		this.dssttitulo = dssttitulo;
	}
	public SeCtStTitulo(String clsttitulo, String dssttitulo, Date fcaudit,
			String usuarioaudit) {
		this.clsttitulo = clsttitulo;
		this.dssttitulo = dssttitulo;
		this.fcaudit = fcaudit;
		this.usuarioaudit = usuarioaudit;
	}

	@Id
	@Column(name = "CLSTTITULO", unique = true, nullable = false, length = 1)
	public String getClsttitulo() {
		return this.clsttitulo;
	}

	public void setClsttitulo(String clsttitulo) {
		this.clsttitulo = clsttitulo;
	}

	@Column(name = "DSSTTITULO", nullable = false, length = 1)
	public String getDssttitulo() {
		return this.dssttitulo;
	}

	public void setDssttitulo(String dssttitulo) {
		this.dssttitulo = dssttitulo;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "FCAUDIT", length = 7)
	public Date getFcaudit() {
		return this.fcaudit;
	}

	public void setFcaudit(Date fcaudit) {
		this.fcaudit = fcaudit;
	}

	@Column(name = "USUARIOAUDIT", length = 30)
	public String getUsuarioaudit() {
		return this.usuarioaudit;
	}

	public void setUsuarioaudit(String usuarioaudit) {
		this.usuarioaudit = usuarioaudit;
	}

}
