package mx.uatx.siiaback.serviciosEscolares.entities;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeCtAreaEstudioOV generated by hbm2java
 */
@Entity
@Table(schema = "SERESC", name = "SECTAREASESTUDIOOV")
public class SeCtAreaEstudioOV implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idareaestudioov;
	private String dsareaestudio;
	private Date fcaudit;
	private String usuarioaudit;
	private Set<SeAxAreaEstudioProgramaOV> seAxAreaEstudioProgramaOVs = new HashSet<SeAxAreaEstudioProgramaOV>(
			0);
	private Set<SeCtMapaOV> seCtMapaOVs = new HashSet<SeCtMapaOV>(0);

	public SeCtAreaEstudioOV() {
	}

	public SeCtAreaEstudioOV(String idareaestudioov, String dsareaestudio) {
		this.idareaestudioov = idareaestudioov;
		this.dsareaestudio = dsareaestudio;
	}
	public SeCtAreaEstudioOV(String idareaestudioov, String dsareaestudio,
			Date fcaudit, String usuarioaudit,
			Set<SeAxAreaEstudioProgramaOV> seAxAreaEstudioProgramaOVs,
			Set<SeCtMapaOV> seCtMapaOVs) {
		this.idareaestudioov = idareaestudioov;
		this.dsareaestudio = dsareaestudio;
		this.fcaudit = fcaudit;
		this.usuarioaudit = usuarioaudit;
		this.seAxAreaEstudioProgramaOVs = seAxAreaEstudioProgramaOVs;
		this.seCtMapaOVs = seCtMapaOVs;
	}

	@Id
	@Column(name = "IDAREAESTUDIOOV", unique = true, nullable = false, precision = 2, scale = 0)
	public String getIdareaestudioov() {
		return this.idareaestudioov;
	}

	public void setIdareaestudioov(String idareaestudioov) {
		this.idareaestudioov = idareaestudioov;
	}

	@Column(name = "DSAREAESTUDIO", nullable = false, length = 100)
	public String getDsareaestudio() {
		return this.dsareaestudio;
	}

	public void setDsareaestudio(String dsareaestudio) {
		this.dsareaestudio = dsareaestudio;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FCAUDIT", length = 7)
	public Date getFcaudit() {
		return this.fcaudit;
	}
	public void setFcaudit(Date fcaudit) {
		this.fcaudit = fcaudit;
	}

	@Column(name = "USUARIOAUDIT", length = 30)
	public String getUsuarioaudit() {
		return this.usuarioaudit;
	}
	public void setUsuarioaudit(String usuarioaudit) {
		this.usuarioaudit = usuarioaudit;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "seCtAreaEstudioOV")
	public Set<SeAxAreaEstudioProgramaOV> getSeAxAreaEstudioProgramaOVs() {
		return seAxAreaEstudioProgramaOVs;
	}

	public void setSeAxAreaEstudioProgramaOVs(
			Set<SeAxAreaEstudioProgramaOV> seAxAreaEstudioProgramaOVs) {
		this.seAxAreaEstudioProgramaOVs = seAxAreaEstudioProgramaOVs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "seCtAreaEstudioOV")
	public Set<SeCtMapaOV> getSeCtMapaOVs() {
		return seCtMapaOVs;
	}
	public void setSeCtMapaOVs(Set<SeCtMapaOV> seCtMapaOVs) {
		this.seCtMapaOVs = seCtMapaOVs;
	}

}
