package mx.uatx.siiaback.serviciosEscolares.entities;
// Generated 9/03/2010 11:26:21 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeAxBloquePreguntaOV generated by hbm2java
 */
@Entity
@Table(schema = "SERESC", name = "SEDTSOLICITUDESEXAMENES")
public class SeDtSolicitudesExamenes implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -4190719516836569720L;

	@Id
	@Basic(optional = false)
	@SequenceGenerator(name = "GENIDDTSOLICITUDEXAMEN", sequenceName = "SERESC.IDDTSOLICITUDEXAMEN", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GENIDDTSOLICITUDEXAMEN")
	@Column(name = "IDDTSOLICITUDEXAMEN")
	private Long lngIdDtSolicitudExamen;

	@JoinColumn(name = "IDSOLICITUDEXAMEN", referencedColumnName = "IDSOLICITUDEXAMEN")
	@ManyToOne
	private SeAxSolicitudesExamenes solicitudExamen;

	@Column(name = "IDALUMNOACTA")
	private Long lngIdAlumnoActa;

	@Column(name = "FCAUDIT")
	@Temporal(TemporalType.TIMESTAMP)
	private Date fcAudit;

	@Column(name = "USUARIOAUDIT", length = 30)
	private String strUsuarioAudit;

	public Long getLngIdDtSolicitudExamen() {
		return lngIdDtSolicitudExamen;
	}

	public void setLngIdDtSolicitudExamen(Long lngIdDtSolicitudExamen) {
		this.lngIdDtSolicitudExamen = lngIdDtSolicitudExamen;
	}

	public SeAxSolicitudesExamenes getSolicitudExamen() {
		return solicitudExamen;
	}

	public void setSolicitudExamen(SeAxSolicitudesExamenes solicitudExamen) {
		this.solicitudExamen = solicitudExamen;
	}

	public Long getLngIdAlumnoActa() {
		return lngIdAlumnoActa;
	}

	public void setLngIdAlumnoActa(Long lngIdAlumnoActa) {
		this.lngIdAlumnoActa = lngIdAlumnoActa;
	}

	public Date getFcAudit() {
		return fcAudit;
	}

	public void setFcAudit(Date fcAudit) {
		this.fcAudit = fcAudit;
	}

	public String getStrUsuarioAudit() {
		return strUsuarioAudit;
	}

	public void setStrUsuarioAudit(String strUsuarioAudit) {
		this.strUsuarioAudit = strUsuarioAudit;
	}

}
