package mx.uatx.siiaback.serviciosEscolares.entities;
// Generated 9/03/2010 11:26:21 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeMsRespuestaCuestionarioOV generated by hbm2java
 */
@Entity
@Table(schema = "SERESC", name = "SEMSRESPUESTASCUESTIONARIOSOV")
public class SeMsRespuestaCuestionarioOV implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id
	@Basic(optional = false)
	@Column(name = "IDRESPUESTACUESTIONARIOOV", unique = true, nullable = false)
	@SequenceGenerator(name = "generadorRespuestaCuestionarioOV", sequenceName = "SERESC.IDRESPUESTACUESTIONARIOOV", allocationSize=1) 
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="generadorRespuestaCuestionarioOV")
	private int idrespuestacuestionarioov;
	
	@Column(name = "IDBLOQUEPREGUNTAOV")
	private Integer seAxBloquePreguntaOV;
	
	@Column(name = "IDRESPUESTAOV")
	private Integer seCtRespuestaOV;
	
	@Column(name = "IDCUESTIONARIOASPIRANTE")
	private Integer seMsCuestionarioAspirante;
	
	@Column(name = "FCAUDIT")
	@Temporal(TemporalType.TIMESTAMP)
	private Date fcaudit;
	
	@Column(name = "USUARIOAUDIT", length = 30)
	private String usuarioaudit;

	
	public SeMsRespuestaCuestionarioOV() {
		super();
	}
	
	public SeMsRespuestaCuestionarioOV(int idrespuestacuestionarioov,
			Integer seAxBloquePreguntaOV,
			Integer seCtRespuestaOV,
			Integer seMsCuestionarioAspirante) {
		this.idrespuestacuestionarioov = idrespuestacuestionarioov;
		this.seAxBloquePreguntaOV = seAxBloquePreguntaOV;
		this.seCtRespuestaOV = seCtRespuestaOV;
		this.seMsCuestionarioAspirante = seMsCuestionarioAspirante;
	}
	
	public SeMsRespuestaCuestionarioOV(int idrespuestacuestionarioov,
			Integer seAxBloquePreguntaOV,
			Integer seCtRespuestaOV,
			Integer seMsCuestionarioAspirante,
			Date fcaudit, String usuarioaudit) {
		this.idrespuestacuestionarioov = idrespuestacuestionarioov;
		this.seAxBloquePreguntaOV = seAxBloquePreguntaOV;
		this.seCtRespuestaOV = seCtRespuestaOV;
		this.seMsCuestionarioAspirante = seMsCuestionarioAspirante;
		this.fcaudit = fcaudit;
		this.usuarioaudit = usuarioaudit;
	}

	

	
	public int getIdrespuestacuestionarioov() {
		return this.idrespuestacuestionarioov;
	}

	public void setIdrespuestacuestionarioov(int idrespuestacuestionarioov) {
		this.idrespuestacuestionarioov = idrespuestacuestionarioov;
	}


	public Integer getSeAxBloquePreguntaOV() {
		return seAxBloquePreguntaOV;
	}



	public void setSeAxBloquePreguntaOV(Integer seAxBloquePreguntaOV) {
		this.seAxBloquePreguntaOV = seAxBloquePreguntaOV;
	}



	public Integer getSeCtRespuestaOV() {
		return seCtRespuestaOV;
	}



	public void setSeCtRespuestaOV(Integer seCtRespuestaOV) {
		this.seCtRespuestaOV = seCtRespuestaOV;
	}



	public Integer getSeMsCuestionarioAspirante() {
		return seMsCuestionarioAspirante;
	}



	public void setSeMsCuestionarioAspirante(Integer seMsCuestionarioAspirante) {
		this.seMsCuestionarioAspirante = seMsCuestionarioAspirante;
	}



	public Date getFcaudit() {
		return fcaudit;
	}



	public void setFcaudit(Date fcaudit) {
		this.fcaudit = fcaudit;
	}



	public String getUsuarioaudit() {
		return usuarioaudit;
	}



	public void setUsuarioaudit(String usuarioaudit) {
		this.usuarioaudit = usuarioaudit;
	}



	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
}
